### ISSUE TITLE
Upload fail on <X> and error in docker login.

### ISSUE THREAD

**Issue by dianlight** [home-assistant/hassio-builder#35]
Hello,
 I have trouble using the builder as documented. I start the build process with the command:

`docker run --rm --privileged -v ~/.docker:/root/.docker -v $(pwd)/${addon}:/data homeassistant/amd64-builder --all -t /data`

and all works but at the end no image is uploaded. I look in the build code and see that the `docket push` is redirected do /dev/null so I'm unble toi check the real error.

> [13:55:22] INFO: Finish build for dianlight/rpi-mysensor-gw-armv7:0.0.19
> [13:55:22] INFO: Create image tag: latest
> [13:55:22] INFO: Start upload dianlight/rpi-mysensor-gw-armv7:0.0.19
> [13:55:24] WARNING: Upload fail on 1
> [13:55:50] INFO: Start upload dianlight/rpi-mysensor-gw-armhf:0.0.19
> [13:55:51] WARNING: Upload fail on 3
> [13:55:54] INFO: Start upload dianlight/rpi-mysensor-gw-armv7:0.0.19
> [13:55:56] WARNING: Upload fail on 2
> [13:56:21] INFO: Start upload dianlight/rpi-mysensor-gw-armhf:latest
> [13:56:24] WARNING: Upload fail on 1
> [13:56:26] INFO: Start upload dianlight/rpi-mysensor-gw-armv7:0.0.19
> [13:56:28] WARNING: Upload fail on 3
> [13:56:54] INFO: Start upload dianlight/rpi-mysensor-gw-armhf:latest
> [13:56:55] WARNING: Upload fail on 2
> [13:56:58] INFO: Start upload dianlight/rpi-mysensor-gw-armv7:latest
> [13:57:00] WARNING: Upload fail on 1
> [13:57:25] INFO: Start upload dianlight/rpi-mysensor-gw-armhf:latest
> [13:57:27] WARNING: Upload fail on 3
> [13:57:30] INFO: Start upload dianlight/rpi-mysensor-gw-armv7:latest
> [13:57:32] WARNING: Upload fail on 2
> [13:58:02] INFO: Start upload dianlight/rpi-mysensor-gw-armv7:latest
> [13:58:03] WARNING: Upload fail on 3

I try to do the docker login in the buildervm with the command `docker run -ti --rm --privileged -v ~/.docker:/root/.docker -v $(pwd)/${addon}:/data homeassistant/amd64-builder --all -t /data --docker-login` but the following error is raised:

> tMacBook-Pro-143 hassio-addons % docker run -ti --rm --privileged -v ~/.docker:/root/.docker -v $(pwd)/${addon}:/data homeassistant/amd64-builder --all -t /data --docker-login 
> [14:02:53] INFO: Setup crosscompiling feature
> [14:02:53] INFO: Starting docker.
> [14:02:53] INFO: Waiting for docker to initialize...
> [14:02:54] INFO: Docker was initialized
> Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
> Username: REMOVED
> Password: 
> **Error saving credentials: error storing credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``**

**Comment by alfredopironti** [comment]
I was experiencing the same, and short story is I solved it by removing the "-v ~/.docker:/root/.docker" option. If you like more details, it goes as follows.

The -v option binds your local .docker configuration folder into the container /root/.docker directory. Likely, in your ~/.docker/config.json file, you have a line like "credsStore": "desktop", which means you use the desktop credentials store, instead of storing your access token into config.json. Since the hassio builder image comes without the desktop credential store, it fails when trying to store your credentials this way.

If you remove that -v option, your local .docker configuration doesn't get mounted in the container. At that point, when you use the --docker-login option, your credentials will be stored plaintext into the container's configuration, and login will succeed. As a consequence, the upload now succeeds for me.

Hope this helps!

**Comment by pgross41** [comment]
I am on Windows with this issue. I tried with and without `-v` in actual Windows as well as WSL. I eventually ran the following workaround to do it manually: 

1. Start an interactive shell in the container: 
```shell
docker run -it --privileged --entrypoint bash homeassistant/amd64-builder
```
2. Run the script:
```shell
/usr/bin/builder.sh --all -t addon-folder -r https://github.com/xy/addons -b branchname
```
3. Manually log into Docker Hub:
```
docker login
```
4. Confirm the image names: 
```
docker images
```
5. Manually upload to Docker Hub: 
```shell
docker push xy/addon-folder-armv7
docker push xy/addon-folder-armhf
docker push xy/addon-folder-aarch64
docker push xy/addon-folder-i386
docker push xy/addon-folder-amd64
```
